#!/bin/sh
. "$(dirname "$0")/_/husky.sh"

echo '🏗️👷 Styling, testing, and building the project before committing'

# Check Prettier standards
npm run check-format ||
(
  echo 'Prettier format-check failed. Run npm run format, add changes and try commit again.';
  false;
)

# Check ESLint Standards
npm run check-lint ||
(
  echo 'ESLint check failed. Make the required changes listed above, add changes and try to commit again.'
  false; 
)

# Check tsconfig standards
npm run check-types ||
(
  echo 'Typescript types-check failed. Make the required changes listed above, add changes and try to commit again.'
  false;
)

# If everything passes... Now we can try to build the project
echo 'All the checks are successfully passed. Building project proceeds next.'

npm run build ||
(
  echo 'Next build failed: view the above errors. '
  false;
)

# If everything passes... Now we can commit
echo '✅✅✅✅ The project was successgully build. The commits are accepted. ✅✅✅✅'npx lint-staged
